wheretogo/maps/urls.py
from django.urls import path
from maps.views import MapView

app_name = "maps"

urlpatterns = [
    path("map/", MapView.as_view(), name="map"),
]

wheretogo/wheretogo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("maps.api")),
    path("accounts/", include("allauth.urls")),
    path("", TemplateView.as_view(template_name="common/index.html")),
    path("maps/", include("maps.urls", namespace="maps")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wheretogo/maps/models.py
from django.contrib.gis.db import models as gis_models
from django.utils.translation import gettext_lazy as _
from django.db import models


class Facility(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    location = gis_models.PointField(
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = _("facility")
        verbose_name_plural = _("facilities")

    def __unicode__(self):
        return self.name

wheretogo/maps/views.py
from django.views.generic.base import TemplateView


class MapView(TemplateView):

    template_name = "maps/map.html"

wheretogo/templates/common/base.html
{% load static %}

{% load i18n %}

<!doctype html>
<html lang="en">

<head>
    <title>{% block head_title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'common/img/favicon.ico' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/base.css' %}" />
    {% block extra_head %}
    {% endblock %}
    {% csrf_token %}
</head>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">WhereToGo</a>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'maps:map' %}">{% trans "Map" %}</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                        {% if user.is_superuser %}
                            <li><a class="dropdown-item" href="{% url 'admin:index' %}">{% trans "Admin page" %}</a></li>
                        {% endif %}
                        <li><a class="dropdown-item" href="{% url 'account_email' %}">{% trans "Change E-mail" %}</a></li>
                        <li><a class="dropdown-item" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                {% endif %}
            </ul>
        </div>    
    </div>
</nav>

<body>

{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible shadow fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
        <span aria-hidden="true"></span>
    </button>
    {{ message | safe }}
</div>
{% endfor %}
{% endif %}

{% block content %}{% endblock %}

{% block scripts %}{% endblock %}

</body>
</html>

wheretogo/templates/common/index.html
{% extends "common/base.html" %}

{% block head_title %}WhereToGo{% endblock %}

wheretogo/templates/maps/map.html
{% extends "common/base.html" %}

{% load static %}

{% block head_title %}WhereToGo{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
crossorigin=""></script>
<link rel="stylesheet" type="text/css" href="{% static 'maps/css/map.css' %}" />
{% endblock %}

{% block content %}
<div class="container-fluid m-0 p-0">
    <div class="row">
        <div class="col-9 p-0">
            <div id="map"></div>
        </div>
        <div class="col-3 p-0">
            <div class="panel">
                <button>Тест</button>
            </div>
        </div>
        </div>
    </div>
</div>
<span id="facilityMarkerURL" style="display: none;">{% static "maps/img/place.png" %}</span>
{% endblock %}

{% block scripts %}
<script src="{% static 'maps/js/map.js' %}"></script>
{% endblock %}